### ISSUE TITLE
Reprendre les éléments clés du site schoolofdata.org

### ISSUE THREAD

**Issue by pzwsk** [ecoledesdonnees/site#19]
Pour l'ensemble du site : 
* Même police : **Open Sans**
* Pas de ligne blanche entre le header et la banner
* Hauteur du header : 80px

Pour la home : 
L'affichage en trois colonnes du dernier blog post, cours, coins arrondis, publié le ... par ... : 

### Couleurs de base : 

- `#00AFF0`
- `#333333`
- `#C9C9C9`

### Autres couleurs : 

- `#B6AAA7` 
- `#23A1D4`

 **Top navigation**
Open Sans Bold 11.5pt
-20 tracking

**Titre : Ecole des Données**
Open Sans Light 43pt/48pt
-40 tracking

**Phrase d’intro**
Open Sans Regular/Bold 18pt/24pt
-20 tracking

**Titre des trois colonnes**
SMALL CAPS
Open Sans Regular 13pt
-20 tracking
Bold text
Open Sans Bold 17pt
-20 tracking

**Titre des articles**
Open Sans Bold 19pt/24pt
-20 tracking

**Date des articles**
Open Sans Regular 8.5pt/20pt
-20 tracking

**Corps des articles (p)**
Open Sans Regular 11pt/15pt
-20 tracking

**Petit bouton call to action**
CAPS
Open Sans Bold 8.5pt
-20 tracking

**Texte du Footer **
Open Sans Semibold 11pt/15pt
-20 tracking

All call-to-action buttons (and some
other elements such as the highlight
images) have 5px rounded corners

<img width="795" alt="capture d ecran 2017-03-30 a 17 34 35" src="https://cloud.githubusercontent.com/assets/6681719/24512991/5620ec1a-1570-11e7-9653-5589ad44e94f.png">

**Comment by cecilaki** [comment]
@Agathesev 

- Meme police = **Open Sans**

Pour le titre "l'École des données" : 
```
    font-weight: 400;
    font-size: 40pt;
    line-height: 43pt;
    margin-bottom: 40px;
```
Pour le paragraphe "Apprendre à rendre les données utiles pour vous, et pour les autres"
(sans guillemets d'ailleurs, non @pzwsk ?)
```
    font-size: 18px;
    line-height: 24px;

```

- Taille du header : passer de 90px actuellement à 80px
--> _Du coup il va falloir réajuster le centrage du logo_

```
@media screen and (min-width: 53.75em)
main.css:212
.site-header {
    **height: 80px;**
```

**Comment by cecilaki** [comment]
@Agathesev  Navigation : 

Les titres ne changent pas de couleur au survol. Ils restent blanc comme ceci : 
- **Style des titres de la navigation**
```
    color: #FFF;
    text-shadow: none;
    font-size: 11.5pt;
    font-weight: 700;
    padding-top: 5px;
    padding-bottom: 5px;
```

C'est juste le background-color qui change comme ceci : 

- **Dropdown :** 
background-color: ` #23A1D4; `
( existing : white ) 
color: `#777777;`

- Les sous-éléments deviennent **blancs** au survol 

<img width="273" alt="capture d ecran 2017-03-30 a 14 03 51" src="https://cloud.githubusercontent.com/assets/6681719/24503335/ec8aaf20-1551-11e7-8cc4-aa3bfbe49448.png">

Pour l'instant : 

<img width="308" alt="capture d ecran 2017-03-30 a 14 06 06" src="https://cloud.githubusercontent.com/assets/6681719/24503366/136951fa-1552-11e7-97a9-4b7458b97bab.png">

<img width="845" alt="capture d ecran 2017-03-30 a 17 33 12" src="https://cloud.githubusercontent.com/assets/6681719/24513613/ef940f98-1571-11e7-9360-e7cb55b37ce7.png">
