### ISSUE TITLE
Ajustement du design des trois parties de la home page

### ISSUE THREAD

**Issue by cecilaki** [ecoledesdonnees/site#5]
**Design guidelines :** 

<img width="458" alt="capture d ecran 2017-02-21 a 10 51 50" src="https://cloud.githubusercontent.com/assets/6681719/23159634/d442f814-f823-11e6-9164-ab621bcd6709.png">

**Design actuel :** 

<img width="819" alt="capture d ecran 2017-02-17 a 02 44 26" src="https://cloud.githubusercontent.com/assets/6681719/23049238/0b940ca2-f4bb-11e6-8ad1-b92e06e48160.png">

**Futur design :** 

<img width="1035" alt="capture d ecran 2017-02-17 a 02 42 39" src="https://cloud.githubusercontent.com/assets/6681719/23049247/1b0d288a-f4bb-11e6-97d4-fb467699a42c.png">

Steps : 

- Rajouter un titre au dessus de l'espace de texte
- Publier un petit extrait du dernier blog post dans le 3è espace

**Comment by Agathesev** [comment]
les 3 colonnes de la même taille aussi

**Comment by cecilaki** [comment]
Aussi. Oups :)

**Comment by cecilaki** [comment]
J'avais en fait réussi à le faire avant qu'on push ton code, du coup il doit y avoir moyen de retrouver le style d'avant :)

**Comment by cecilaki** [comment]
Bingo, en voilà une partie : [voir les détails sur ce diff](https://github.com/ecoledesdonnees/site/commit/58dd0bbf54d160ae379246c0f3fdc97bc7a9afd4#diff-57823f3d19b168e73527501054166fbf)

<img width="534" alt="capture d ecran 2017-03-30 a 14 41 13" src="https://cloud.githubusercontent.com/assets/6681719/24504578/1d460c68-1557-11e7-8b2e-aa4c8b1db4de.png">

**Comment by cecilaki** [comment]
Et voilà le reste : 

<img width="512" alt="capture d ecran 2017-03-30 a 14 44 39" src="https://cloud.githubusercontent.com/assets/6681719/24504691/840e6bfc-1557-11e7-8dd1-6fad2aa3b405.png"> 

et aussi pour terminer :  

<img width="845" alt="capture d ecran 2017-03-30 a 14 45 03" src="https://cloud.githubusercontent.com/assets/6681719/24504703/905cb404-1557-11e7-8e14-7f0b02dcf244.png">

Tout est [ici donc](https://github.com/ecoledesdonnees/site/commit/58dd0bbf54d160ae379246c0f3fdc97bc7a9afd4#diff-57823f3d19b168e73527501054166fbf).
